### PR TITLE
subtree = root:add(p_QV24T

### PR DESCRIPTION
**Pull request by shruggie**

### CODE REVIEW

**Comment by ZL4JY** [comment]
I don't understand the issue you are seeing.  Can you explain further please?

John

**Comment by shruggie** [comment]
I changed subtree = root:add(p_QV24, buf(9))  to subtree = root:add(p_QV24T, buf(9)) otherwise I see Quantar V.24 over UDP for TCP packets or if Qv24_TCP.lua is disabled it displays NULL:

**Comment by ZL4JY** [comment]
Thanks.

**Comment by shruggie** [comment]
No problem, thank you for this nice tool.

Alex, DC5AJ

2016-09-07 10:46 GMT+02:00 John Yaldwyn notifications@github.com:

**Pull request merged**
